# Smartgrid mit Lego-Mindstrom#
##Einleitung##
Das Smart-Grid ist ein sehr  vielseitiger und auch komplexer Themenkreis, der sich auf verschiedenen  Ebenen im Informatikunterricht bearbeiten lässt. Für Schulen die über  Lego Mindstorms verfügen können sich auf dieser Ebene mit dem Thema  Smart-Grid befassen.
Die Energiewende ist zur Zeit ein wichtiges Thema in der gesellschaftlichen Diskussion. Kernfrage dieser Diskussion ist die Gestaltung der zukünftigen Stromerzeugung und Stromverteilung. An diesem Punkt steht das Stromnetz im Fokus. Hier soll sich einiges ändern. Weg vom konventionellen verbrauchsgesteuertem Netz hin zum intelligenten erzeugergesteuertem Netz, auch Smart-Grid genannt.
Damit das Netz "Smart" wird, ist die Informatik deutlich stärker als bisher gefordert. In Zukunft müssen Daten über Erzeugung und Bedarf an Strom ausgetauscht werden und denzentrale Netze koordiniert werden.
Die folgende Sequenz enthält drei Module in denen sich die Schüler ausgehend von Lego-Mindstorms mit dem Thema Smart-Grid auseinandersetzen. Am Ende der Sequenz können die Schülerinnen und Schüler das Konzept des Smart-Grid erklären. Sie kennen den Modellierungskreislauf und den Unterschied zwischen realer Welt und virtueller Umgebung. 
Auf diesem Wissenstand kann aufgebaut werden.
##Modul 1: Regenerative Energien im Legomodell - Ein spielerischer Einstieg##
Zum Einstieg in das Thema steht zunächst ein spielerischer Einstieg mit Lego an. Kernpunkt sind Experimente mit einem Versuchsaufbau aus Lego. Der Aufbau umfasst zwei Experimente zur Erzeugung von regenerativen Energien. Zum ein wird die Stromerzeugung, durch ein Windrad betrachtet und zum anderen die Stromerzeugung durch eine Solarzelle. Konzeptionell sind die Experimente sehr identsich, so dass es ausreichend ist, wenn  die Schülerinnen und Schüler nur eines der beiden Experimente durchführen. Allerdings kann die Erkenntnisgewinnung und das Kompetenzerleben durch die Bearbeitung beider Experimente gesteigert werden.
An diesen Experimenten erlernen die Schülerinnen und Schüler neben den Grundlagen der regenerativen Energien auch den Umgang mit der Lego-Hardware. Dies ist Grundlage für die weiterführenden Module der Sequenz.
Zur Durchführung der Experimente werden Arbeitsblätter verwendet, mit denen die Schülerinnen und Schüler die Experimente selbstständig an Stationen durchzuführen. Die Experimente sind so ausgelegt, dass die Schülerinnen und Schüler 
